from_eng_to_rus_day_week = {
    'Sunday': 'воскресенье', 'Monday': 'понедельник', 'Tuesday': 'вторник', 'Wednesday': 'среда',
    'Thursday': 'четверг', 'Friday': 'пятница', 'Saturday': 'суббота'
}
ADMIN_TIME_SCHEDULE_BUTTON = 'Расписание'
TAKE_LESSON_BUTTON = 'Записаться на занятие'
MY_DATA_BUTTON = 'Мои данные'
SKIP_LESSON_BUTTON = 'Пропустить занятие'

SELECT_DAY_TO_SHOW_COACH_SCHEDULE = 'COACH_SCHEDULE'
SHOW_GROUPDAY_INFO = 'GROUPDAY_INFO'

SET_UP_TIME_BEFORE_CANCEL_BUTTON = 'TIME_BEFORE_CANCEL'
SET_UP_PLAYER_STATUS = 'PLAYER_STATUS'

SELECT_SKIP_TIME_BUTTON = 'SELECT_SKIP_TIME'
SHOW_INFO_ABOUT_SKIPPING_DAY = 'INFO_SKIPPING_DAY'

SELECT_TRAINING_TYPE = 'SELECT_TRAINING_TYPE'

SELECT_GROUP_LESSON_TIME = 'SELECT_GROUP_LESSON'
SELECT_PRECISE_GROUP_TIME = 'SELECT_PRECISE_GROUP_TIME'
CONFIRM_GROUP_LESSON = 'CONFIRM_GROUP'

SELECT_DURATION_FOR_IND_TRAIN = 'SELECT_DURATION_FOR_IND_TRAIN'
SELECT_IND_LESSON_TIME = 'SELECT_IND_LESSON_TIME'
SELECT_PRECISE_IND_TIME = 'IND_TIME'
PERMISSION_FOR_IND_TRAIN = 'PERMISSION_IND_TRAIN'


