from_eng_to_rus_day_week = {
    'Sunday': 'воскресенье', 'Monday': 'понедельник', 'Tuesday': 'вторник', 'Wednesday': 'среда',
    'Thursday': 'четверг', 'Friday': 'пятница', 'Saturday': 'суббота'
}

SET_UP_TIME_BEFORE_CANCEL_BUTTON = 'TIME_BEFORE_CANCEL'
SET_UP_PLAYER_STATUS = 'PLAYER_STATUS'

SELECT_SKIP_TIME_BUTTON = 'SELECT_SKIP_TIME'
SELECT_GROUP_LESSON_TIME = 'SELECT_GROUP_LESSON'
SELECT_PRECISE_GROUP_TIME = 'SELECT_PRECISE_GROUP_TIME'
SELECT_IND_LESSON_TIME = 'SELECT_IND_LESSON_TIME'
SELECT_PRECISE_IND_TIME = 'IND_TIME'

SELECT_TRAINING_TYPE = 'SELECT_TRAINING_TYPE'
SELECT_DURATION_FOR_IND_TRAIN = 'SELECT_DURATION_FOR_IND_TRAIN'

PERMISSION_FOR_IND_TRAIN = 'PERMISSION_IND_TRAIN'
