# Generated by Django 2.0.5 on 2020-07-14 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouptrainingday',
            name='absent',
            field=models.ManyToManyField(blank=True, help_text='Кто сегодня отсутствует', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='grouptrainingday',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата Занятия'),
        ),
        migrations.AlterField(
            model_name='grouptrainingday',
            name='duration',
            field=models.TimeField(blank=True, help_text='H:M:S', null=True, verbose_name='Продолжительность занятия'),
        ),
        migrations.AlterField(
            model_name='grouptrainingday',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.TrainingGroup', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='grouptrainingday',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Будет ли в этот день тренировка у этой группы'),
        ),
        migrations.AlterField(
            model_name='grouptrainingday',
            name='start_time',
            field=models.TimeField(blank=True, help_text='H:M:S', null=True, verbose_name='Время начала занятия'),
        ),
    ]
