# Generated by Django 2.0.5 on 2020-07-16 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20200715_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='time_before_cancel',
            field=models.DurationField(help_text='D H:M:S', null=True),
        ),
    ]
