# Generated by Django 2.0.5 on 2020-08-12 18:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20200801_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traininggroup',
            name='tarif',
        ),
        migrations.AlterField(
            model_name='grouptrainingday',
            name='duration',
            field=models.DurationField(default='1:0:0', help_text='ЧАСЫ:МИНУТЫ:СЕКУНДЫ', null=True, verbose_name='Продолжительность занятия'),
        ),
        migrations.AlterField(
            model_name='grouptrainingday',
            name='visitors',
            field=models.ManyToManyField(blank=True, help_text='Пришли из других групп\n', related_name='visitors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Tarif',
        ),
    ]
