# Generated by Django 2.0.5 on 2020-08-18 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20200812_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='time_before_cancel',
            field=models.DurationField(default='6:0:0', help_text='ЧАСЫ:МИНУТЫ:СЕКУНДЫ', null=True, verbose_name='Время, за которое нужно предупредить'),
        ),
    ]
