# Generated by Django 2.0.5 on 2020-08-18 09:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20200818_0712'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouptrainingday',
            name='dttm_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='grouptrainingday',
            name='dttm_deleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grouptrainingday',
            name='tr_day_status',
            field=models.CharField(default='M', help_text='Моя тренировка или аренда', max_length=1, verbose_name='Статус'),
        ),
    ]
