# Generated by Django 2.0.5 on 2020-08-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_auto_20200825_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouptrainingday',
            name='is_individual',
            field=models.BooleanField(default=False, help_text='индивидуальная ли тренировка'),
        ),
    ]
