# Generated by Django 2.0.5 on 2020-09-04 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_insert_static_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='traininggroup',
            name='status',
            field=models.CharField(default='G', max_length=1, verbose_name='Статус группы'),
        ),
        migrations.AddField(
            model_name='user',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='traininggroup',
            name='name',
            field=models.CharField(max_length=32, verbose_name='Название'),
        ),
    ]
