# Generated by Django 2.0.5 on 2020-09-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_set_group_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traininggroup',
            name='status',
            field=models.CharField(choices=[('I', 'для индивидуальных тренировок'), ('G', 'взрослые групповые тренировки'), ('F', 'детская группа малой численности'), ('S', 'детская секция')], default='G', max_length=1, verbose_name='Статус группы'),
        ),
    ]
