# Generated by Django 2.0.5 on 2020-09-04 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_traininggroup_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traininggroup',
            name='level',
            field=models.CharField(choices=[('G', '🍏мяч🍏'), ('O', '\U0001f9e1мяч\U0001f9e1')], default='O', max_length=1, verbose_name='Уровень группы'),
        ),
    ]
