# Generated by Django 2.0.5 on 2020-09-05 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_auto_20200904_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='amount',
        ),
        migrations.AddField(
            model_name='payment',
            name='fact_amount',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='Сколько заплатил'),
        ),
        migrations.AddField(
            model_name='payment',
            name='n_fact_visiting',
            field=models.PositiveSmallIntegerField(default=0, null=True, verbose_name='Кол-во посещенных занятий'),
        ),
        migrations.AddField(
            model_name='payment',
            name='theory_amount',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='Сколько должен был заплатить'),
        ),
        migrations.AlterField(
            model_name='user',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to=settings.AUTH_USER_MODEL, verbose_name='Родитель'),
        ),
    ]
