# Generated by Django 2.0.5 on 2020-09-08 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_auto_20200905_1811'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarif_ind', models.PositiveIntegerField(default=1400, null=True, verbose_name='Индивидуальный тариф')),
                ('tarif_group', models.PositiveIntegerField(default=400, null=True, verbose_name='Групповой взрослый тариф')),
                ('tarif_arbitrary', models.PositiveIntegerField(default=600, null=True, verbose_name='Тариф для свободного графика')),
                ('tarif_few', models.PositiveIntegerField(default=400, null=True, verbose_name='Тариф для детской группы малой численности')),
                ('tarif_section', models.PositiveIntegerField(default=4000, null=True, verbose_name='Тариф для детской секции в месяц')),
            ],
            options={
                'verbose_name': 'Изменяемые данные',
                'verbose_name_plural': 'Изменяемые данные',
            },
        ),
    ]
